### ISSUE TITLE
Is it possible to create a lightweight landmark detection model using this repo?

### ISSUE THREAD

**Issue by Keiku** [SeungyounShin/Adaptive-Wing-Loss-for-Robust-Face-Alignment-via-Heatmap-Regression#1]
I want to make a lightweight landmark detection model like [OpenSeeFace](https://github.com/emilianavt/OpenSeeFace), but there is no training code in OpenSeeFace repo. Your repo has only HourglassNet, but can you make a lightweight model for mobile? Do you have any idea what is good if you make it?

**Comment by SeungyounShin** [comment]
DLA(deep layer aggregation) is recommended or you can stack fewer HG(hourglass) to make the model more light. however, recent approaches are focused on knowledge distillation. 

+ 4HG inference time on andriod 1.2s

**Comment by Keiku** [comment]
Thank you for your answer. It will be helpful.
